name: Sync Fork

on:
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch:

jobs:
  sync:
     runs-on: ubuntu-latest

     permissions:
       contents: write

     steps:
       - uses: actions/checkout@v4
       - run: git remote add upstream https://github.com/Hanover-CS/HC26-Burchett-Matt-Senior-Project.git
       - run: git pull --rebase upstream main
       - run: git push --force
       
